# Retorna todos os usuarios
###
GET http://localhost:3003/users

# Retorna todos os produtos
###
GET http://localhost:3003/products

# Cadastra novo usuario
###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"teste2",
    "email":"email2@email.com",
    "password": "tesenha2"
}

# Cadastra um novo produto
###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "manteiga arabica",
    "price": 100,
    "imageUrl": "teste3"
}

# Faz uma compra para o usuario
###
POST http://localhost:3003/purchase
Content-Type: application/json

{
    "userId": "75b07484-e543-4b99-9b0f-10c0f5c32142",
    "productId": "9bcf03aa-68e9-4c44-ab8e-0ad4d169d108",
    "quantity": 4
}