# Retorna todos os usuarios
###
GET http://localhost:3003/users

# Retorna todos os produtos
###
GET http://localhost:3003/products?search=pera

# Retorna as compras de um usuario
###
GET http://localhost:3003/users/92432666-cb2a-4957-995f-c675d92db2c5/purchases

# Cadastra novo usuario
###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"teste2",
    "email":"email2@email.com",
    "password": "tesenha2"
}

# Cadastra um novo produto
###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "iPera 12",
    "price": 10000,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTKG0AMROn_9kTgWyUCaysl8vklLL63r471_xHNID1wk33f9hoWKua9_A2iFoCQXspofAvzQsxnAFY&usqp=CAc"
}

# Faz uma compra para o usuario
###
POST http://localhost:3003/purchase
Content-Type: application/json

{
    "userId": "92432666-cb2a-4957-995f-c675d92db2c5",
    "productId": "78e04429-2a83-49a9-ad7d-ea83a2229bb8",
    "quantity": 1
}